
### Pedro Arrizon 

## LU factorization 

lets say our Matrix ($A$) is defined as shown:



$ A = \begin{bmatrix}
1 & 2 & -1\\
2 & 1 & -2 \\
-3 & 1 & 1
\end{bmatrix}$



Our goal with LU factorization is to represent matrix $A$ by two other matrixes $L\& U$. The benefit of factorization is that we are able to have a matrix representation of the operations we do to matrix $A$.



### Upper Triangular Matrix $U$

We use Gaussian Elimination of matrix $A$ to reduce it into an **Upper triangular** matrix as shown below. 

- We would define $U$ as the upper matrix:

$ U = \begin{bmatrix}
1 & 2 & -1\\
0 & -3 & 0 \\
0 & 0 & -2
\end{bmatrix}$

| We can also say a matrix is **Upper triangular** if it's entries satisfy **($u_{ij} = 0 \ for \ i>j$.)**


### Lower Triangular Matrix $L$

While we are doing matrix operations on matrix $A$ to try and get it into the upper triangular form $U$ our matrix $L$ is formed. The Lower Triangular Matrix $L$ stores the matrix calculations it takes to get matrix $A$ into the upper triangular form $U$.

- We would define $L$ as a lower triangular matrix: 

$ L = \begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0 \\
-3 & -\frac{7}{3} & 1
\end{bmatrix}$

| A matrix can be defined as lower triangular if its entries satisfy **($l_{ij} = 0 \ for \ i>j$.)**



#### Therefore $LU = A$

Once we know $L$ and $U$ the problem $Ax=b$ becomes easier to solve by using **two step back substitution**

1. Solve $Lc = b$, for c
2. Solve $Ux = c$, for x

## Complexity and time

If we wanted to solve for multiple $b's$ for our system $Ax$ how would we know how many operations or how long it would take?

For all $b$ in $b_k$:
- Classical Gaussian elimination approximately $ \frac{2kn^3}{3}$ operations.
- Using LU approximately $ \frac{2n^3}{3} + 3kn^2$ operations.

In [4]:
import pprint
import numpy as np
import scipy.linalg   

A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)

print ("A:")
pprint.pprint(A)

print ("P:")
pprint.pprint(P)  #this is permutation matrix which just tracks the row switches done

print ("L:")
pprint.pprint(L)

print ("U:")
pprint.pprint(U)

A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
U:
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])


C:\Users\arriz\AppData\Local\Temp/ipykernel_20588/2061367040.py:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
